AllCops:
  TargetRubyVersion: 2.1

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 300

Metrics/AbcSize:
  Max: 57

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Style/NumericLiterals:
  MinDigits: 7

Style/AsciiComments:
  Enabled: false

Style/ParameterLists:
  Max: 15
